server:
  servlet:
    context-path: /api


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pfedatabase?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: toor
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB




  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect